"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(23, 34);
var myPoint2 = new point_1.Point(87, 27);
var myPoint3 = new point_1.Point(13, 15);
var myPoint4 = new point_1.Point(98, 24);
var arrPoint = [myPoint2, myPoint3, myPoint4];
console.log(myPoint.toString());
console.log(myPoint.distanceTolOrigin());
console.log(myPoint.calculateDistance(myPoint2));
console.log(myPoint2.calcularQuadrant());
var pointCercano = myPoint.calculateNearest(arrPoint);
console.log(pointCercano.toString());
